-- HyprNotch keybinds — generated by install.sh. DO NOT EDIT: the
-- Settings → Keybinds editor rewrites this file on every change, and
-- install.sh rewrites it on update.
--
-- Written for the k4 Lua fork of Hyprland (hyprland.lua configs). The
-- same binds exist in sample-hyprland.conf for classic .conf users.
--
-- To revert: delete this file and the `require("config.hyprnotch")`
-- line in hyprland.lua.
--
-- If a shortcut collides with one of yours, yours wins when defined
-- AFTER this require line.

local mod = "SUPER"
local raiz = "@RAIZ@"

--  The IPC target. `quickshell ipc` is the subcommand — without it the
--  bind fires nothing and the keypress falls through.
local notch = "quickshell ipc -p " .. raiz .. "/shell.qml call notch "

----------------------------------------------------------------------------
-- Startup
----------------------------------------------------------------------------
--  start.sh syncs the downloaded folder into the installed copy first,
--  so launching it (and not quickshell directly) can never run a stale
--  build. It also seeds the state directories.
hl.on("hyprland.start", function()
    hl.exec_cmd(raiz .. "/start.sh")
end)

----------------------------------------------------------------------------
-- The island
----------------------------------------------------------------------------
--  Super+Space opens the launcher — a plain chord, no release-bind
--  magic, so it behaves identically on mainline Hyprland and the k4
--  Lua fork. Every chord here is editable LIVE in Settings → Keybinds
--  (which rewrites this file); this template is only the bootstrap.
hl.bind(mod .. " + SPACE",  hl.dsp.exec_cmd(notch .. "launcher"))
hl.bind(mod .. " + C",      hl.dsp.exec_cmd(notch .. "controlCenter"))
hl.bind(mod .. " + K",      hl.dsp.exec_cmd(notch .. "calendar"))
hl.bind(mod .. " + N",      hl.dsp.exec_cmd(notch .. "notifications"))
hl.bind(mod .. " + W",      hl.dsp.exec_cmd(notch .. "weather"))
hl.bind(mod .. " + T",      hl.dsp.exec_cmd(notch .. "stats"))
hl.bind(mod .. " + G",      hl.dsp.exec_cmd(notch .. "wallpaper"))
hl.bind(mod .. " + E",      hl.dsp.exec_cmd(notch .. "power"))
hl.bind(mod .. " + I",      hl.dsp.exec_cmd(notch .. "about"))
hl.bind(mod .. " + O",      hl.dsp.exec_cmd(notch .. "plugins"))
hl.bind(mod .. " + S",      hl.dsp.exec_cmd(notch .. "settings"))
hl.bind(mod .. " + B",      hl.dsp.exec_cmd(notch .. "dnd"))
hl.bind(mod .. " + P",      hl.dsp.exec_cmd(notch .. "podman"))
